---
- template: src=loadbalancer-port80.j2 dest=/etc/nginx/sites-available/loadbalancer-port80
  notify: 
    - restart nginx

#- template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream.conf
#  notify:
#    - restart nginx

- file: src=/etc/nginx/sites-available/loadbalancer-port80 dest=/etc/nginx/sites-enabled/loadbalancer-port80 state=link

- file: path=/etc/nginx/sites-enabled/default state=absent

- name: Start Nginx
  service:
    name: nginx
    state: started




