---
- template: src=webserver-port80.j2 dest=/etc/nginx/sites-available/webserver-port80
  notify: 
    - restart nginx

- template: src=index.html.j2 dest=/usr/share/nginx/html/index.html

- file: src=/etc/nginx/sites-available/webserver-port80 dest=/etc/nginx/sites-enabled/webserver-port80 state=link

- file: path=/etc/nginx/sites-enabled/default state=absent

- name: Start Nginx
  service:
    name: nginx
    state: started




